//login
export const FETCH_LOGIN_RESULT = 'FETCH_LOGIN_RESULT';
export const RECEIVE_LOGIN_RESULT = 'RECEIVE_LOGIN_RESULT';
export const CHANGE_LOGIN_AUTH = 'CHANGE_LOGIN_AUTH';
export const LOGIN_OUT = 'LOGIN_OUT';

export const SWITCH_TAB = 'SWITCH_TAB';
export const SWITCH_TITLE_BAR_TAB = 'switch_title_bar_tab';
export const HOME_TABS = {
  GAME: 'GAME',
  ABOUT: 'ABOUT',
  Data: 'Data',
  ME: 'ME',
};

//Competition 联赛
export const GET_COMPETITION_INFO = 'GET_COMPETITION_INFO';
export const GET_ALL_COMPETITION = 'GET_ALL_COMPETITION';

export const DATA = {
  SWITCH_TITLE_BAR_TAB: 'DATA.TITLE_BAR_TAB',
  COMPETITION: 'DATA.COMPETITION',
  DETAIL: {TEAM:'DATA.DETAIL.TEAM',PLAYERS:'DATA.DETAIL.PLAYERS'},
  LODING: 'DATA.LODING'
}
